import React from 'react';
import { clinic } from './content.js';
import { Arrow, Button, Photo, Breadcrumb, Intro, ServiceList, RouteBlock, NightBlock, FAQ } from './components.jsx';

export function Home() {
  return <><section className="hero"><div><span className="eyebrow">КРУГЛОСУТОЧНАЯ ВЕТЕРИНАРНАЯ КЛИНИКА</span><h1>Клиника рядом.<br />В любое время.</h1><p>Ночью перед приездом позвоните в клинику.</p><div className="actions"><Button light /><a className="text-link" href="/visit">Плановый приём <Arrow /></a></div></div><div className="big-hours"><strong>24/7</strong><p>Армавир<br />Каспарова, 27/2</p></div></section>
    <RouteBlock /><section className="section services"><div className="section-heading"><span className="eyebrow">ПОМОЩЬ ПИТОМЦАМ</span><h2>От первого приёма<br />до восстановления.</h2></div><ServiceList /><a className="text-link" href="/prices">Посмотреть прейскурант <Arrow /></a></section>
    <section className="editorial warm"><Photo name="konstantin-cat-original" portrait alt="Константин Валерьевич Темичев с котом" /><div><span className="eyebrow">ЛЮДИ, КОТОРЫМ ВЫ ДОВЕРЯЕТЕ ПИТОМЦА</span><h2>Знакомство<br />до первого визита.</h2><p>В TemichevVET работают 15 человек. Среди них — 10 ветеринарных специалистов и два кандидата ветеринарных наук.</p><p className="person-name">Константин Валерьевич Темичев</p><p className="small">Руководитель клиники, ветеринарный врач,<br />кандидат ветеринарных наук</p><a className="text-link" href="/team">О команде клиники <Arrow /></a></div></section>
    <section className="section visit-teaser"><span className="eyebrow">ПЕРЕД ПРИЁМОМ</span><h2>Меньше сборов<br />в последний момент.</h2><p>Документы, прежние назначения, вопросы врачу — короткий список поможет ничего не забыть.</p><Button href="/visit">Подготовиться к визиту</Button></section>
    <section className="review-teaser section"><div><span className="eyebrow">ОПЫТ ВЛАДЕЛЬЦЕВ ПИТОМЦЕВ</span><h2>Что говорят<br />после визита.</h2></div><div><p>Отзывы о клинике — на Яндекс Картах. Там можно прочитать подробные истории и оставить свой отзыв.</p><a className="text-link" href="/reviews">Читать отзывы <Arrow /></a></div></section><NightBlock /></>;
}
export function About() {
  return <><Breadcrumb title="О клинике" /><Intro label="TEMICHEVVET · АРМАВИР" title={<>Клиника, в которую<br />можно приехать.</>}><p>Работаем в Армавире с 1996 года. Принимаем питомцев на Каспарова, 27/2 — круглосуточно.</p></Intro><section className="wide-photo"><Photo name="reception-real" alt="Реальная зона ожидания и стойка администратора клиники" priority /></section><section className="section two-columns"><h2>Осмотр. Обследования.<br />Дальнейшее лечение.</h2><div className="prose"><p>В клинике есть лаборатория, УЗИ и рентген, хирургия и стационар. Какие из этих возможностей нужны вашему питомцу, врач определит после осмотра.</p><p>Мы собрали услуги на отдельных страницах: можно заранее посмотреть, как проходит визит, что взять с собой и где уточнить стоимость.</p><a className="text-link" href="/services">Услуги клиники <Arrow /></a></div></section><section className="facts warm"><div><strong>1996</strong><p>год начала работы</p></div><div><strong>15</strong><p>человек в команде</p></div><div><strong>24/7</strong><p>круглосуточная работа</p></div></section><section className="editorial"><Photo name="laboratory-real" alt="Лаборатория клиники" /><div><span className="eyebrow">НАСТОЯЩАЯ КЛИНИКА</span><h2>Посмотрите,<br />как всё устроено.</h2><p>На сайте — фотографии наших помещений и оборудования. Лаборатория и стационар показаны такими, какими их увидят посетители клиники.</p><a className="text-link" href="/services/inpatient">О стационаре <Arrow /></a></div></section><NightBlock /></>;
}
export function Services() {
  return <><Breadcrumb title="Услуги" /><Intro label="ПОМОЩЬ ПИТОМЦАМ" title="С чего начнём?"><p>Если не знаете, какой специалист или обследование нужны, начните с приёма. При записи расскажите, что беспокоит питомца.</p></Intro><section className="section services"><ServiceList /></section><section className="section two-columns"><h2>Стоимость —<br />до визита.</h2><div><p>В прейскуранте можно найти услугу по названию или категории. Состав обследования и лечения зависит от состояния питомца.</p><Button href="/prices">Открыть прейскурант</Button></div></section><NightBlock /></>;
}
export function ServicePage({ service: s }) {
  return <><Breadcrumb title={s.title} parent={['/services', 'Услуги']} /><section className={`detail-hero ${s.image ? '' : 'text-only'}`}><div><span className="eyebrow">TEMICHEVVET · {s.title.toLocaleUpperCase('ru')}</span><h1>{s.title}</h1><p className="lead">{s.intro}</p><p>{s.text}</p><div className="actions"><Button href="/visit">Запланировать визит</Button><a className="text-link" href={clinic.tel}>Позвонить <Arrow /></a></div></div>{s.image && <Photo name={s.image} alt={s.alt} priority />}</section><nav className="anchor-nav" aria-label="На этой странице"><a href="#included">О направлении</a><a href="#prepare">Подготовка</a><a href="#cost">Стоимость</a><a href="#questions">Вопросы</a></nav><section className="section two-columns" id="included"><h2>О направлении</h2><div className="ruled-list">{s.details.map((text, i) => <div key={text}><span className="index">0{i + 1}</span>{text}</div>)}</div></section><section className="section two-columns warm" id="prepare"><h2>Перед приездом</h2><div className="prose"><p>{s.prepare}</p><a href="/visit" className="text-link">Что взять с собой <Arrow /></a></div></section><section className="section two-columns" id="cost"><h2>Стоимость</h2><div><p>{s.slug === 'pharmacy' ? 'Наличие и стоимость препаратов уточните по телефону.' : 'Посмотрите цены на услуги. Если указан диапазон, точная сумма зависит от конкретной процедуры. Состав лечения уточняйте у врача.'}</p><Button href={s.slug === 'pharmacy' ? clinic.tel : `/prices?q=${encodeURIComponent(s.search)}`}>{s.slug === 'pharmacy' ? 'Позвонить в клинику' : 'Посмотреть цены'}</Button></div></section><section className="section two-columns services" id="questions"><h2>Частые вопросы</h2><FAQ entries={s.faq} /></section></>;
}
export function Team({ doctor = false }) {
  return <><Breadcrumb title={doctor ? 'Константин Темичев' : 'Команда'} parent={doctor ? ['/team', 'Команда'] : undefined} />{!doctor && <Intro label="КОМАНДА TEMICHEVVET" title={<>Не один врач.<br />Целая команда.</>}><p>В клинике работают 15 человек. Среди них — 10 ветеринарных специалистов и два кандидата ветеринарных наук.</p></Intro>}<section className="editorial warm team-hero"><Photo name="konstantin-cat-original" portrait alt="Константин Валерьевич Темичев с котом" priority /><div><span className="eyebrow">РУКОВОДИТЕЛЬ КЛИНИКИ</span>{doctor ? <h1>Константин<br />Валерьевич Темичев</h1> : <h2>Константин<br />Валерьевич Темичев</h2>}<p>Ветеринарный врач,<br />кандидат ветеринарных наук</p><p>Если хотите записаться к Константину Валерьевичу, сообщите об этом администратору: он уточнит расписание и предложит время приёма.</p><Button href={doctor ? clinic.tel : '/team/temichev'}>{doctor ? 'Уточнить время приёма' : 'Познакомиться с врачом'}</Button></div></section><section className="section two-columns"><h2>К кому записаться?</h2><div><p>Расскажите администратору о причине обращения. Если у питомца уже есть лечащий врач или направление, скажите об этом при звонке.</p><a className="text-link" href="/visit">О плановом приёме <Arrow /></a></div></section></>;
}
export function Night() {
  return <><Breadcrumb title="Ночной приём" /><Intro label="КЛИНИКА РАБОТАЕТ 24/7" title={<>Ночью тоже<br />можно обратиться.</>}><p>С 20:00 до 09:00 перед приездом обязательно позвоните. Сообщите, что произошло и как чувствует себя питомец.</p><Button light /></Intro><section className="section two-columns"><h2>Что сказать<br />при звонке</h2><div className="ruled-list">{['Кто ваш питомец и сколько ему лет', 'Что произошло и когда это началось', 'Что изменилось в его состоянии', 'Какие препараты он уже получил'].map((s, i) => <div key={s}><span className="index">0{i+1}</span>{s}</div>)}</div></section><RouteBlock detailed /><section className="section warm"><h2>Не ждите ответа через сайт.</h2><p className="measure spaced">Если помощь нужна сейчас, звоните. Сайт не оценивает состояние питомца и не заменяет осмотр врача.</p><Button /></section></>;
}
export function Contacts() {
  return <><Breadcrumb title="Контакты" /><Intro label="АРМАВИР · КАСПАРОВА, 27/2" title={<>До встречи<br />в клинике.</>}><p>Работаем круглосуточно. Ночью перед приездом позвоните.</p><a className="contact-number" href={clinic.tel}>{clinic.phone}</a></Intro><RouteBlock detailed /><section className="section two-columns warm"><h2>Планируете визит?</h2><div><p>Администратор поможет выбрать время и уточнит, что нужно взять с собой.</p><a href="/visit" className="text-link">Подготовка к приёму <Arrow /></a></div></section></>;
}
export function PhotoPlan() {
  return <><Intro label="РАБОЧИЙ МАТЕРИАЛ · НЕ ДЛЯ ПУБЛИКАЦИИ" title="Фотографии, которые добавим"><p>На публичных страницах нет выдуманных портретов или оборудования. Эти места зарезервированы для съёмки.</p></Intro><section className="section photo-plan">{[['Команда клиники', 'Один общий кадр в клинике. Для страниц «Команда» и «О клинике».'], ['Портреты специалистов', 'По одному портрету и согласованной карточке каждого врача.'], ['Операционная и оборудование', 'Общий план и реальные детали оборудования. Для страницы хирургии.'], ['Рентген-кабинет', 'Аппарат и помещение без персональных данных пациентов. Для диагностики.']].map(([title, text], i) => <article key={title}><div className="photo-slot"><span>МЕСТО ДЛЯ ФОТОГРАФИИ</span><strong>0{i+1}</strong></div><h2>{title}</h2><p>{text}</p></article>)}</section></>;
}
